name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  comment:
    permissions:
      checks: write  # Required for creating check runs
      issues: write  # Required for creating/managing labels
      contents: write # releases
      pull-requests: write # pr comments
      statuses: write  # Required for creating commit statuses
    uses: ./.github/workflows/2_pr_comment.yaml
    # secrets: inherit
    with:
      pr_number: ${{ github.event.pull_request.number }}
      message: "👋 Thanks for your PR! We'll review it soon."
