name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  comment:
    uses: ./.github/workflows/2_pr_comment.yaml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      message: "👋 Thanks for your PR! We'll review it soon."
