name: PR Comment

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: number
        description: 'The pull request number to comment on.'
      message:
        required: true
        type: string
        description: 'The message to post in the pull request comment.'

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ inputs.pr_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${{ inputs.message }}"
            })
