name: Create Release

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
        description: "The tag name for the release."
      body:
        required: false
        type: string
        description: "The body text for the release."
        default: "No release notes provided."

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ inputs.tag_name }}",
              name: "${{ inputs.tag_name }}",
              body: "${{ inputs.body }}",
            })
