name: Set Labels

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: number
        description: "The pull request number to add labels to."
      labels:
        required: true
        type: string
        description: "Comma-separated list of labels to add to the pull request."

permissions:
  issues: write
  pull-requests: write

jobs:
  set_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Set Labels
        uses: actions/github-script@v7
        with:
          script: |
            const labelsString = '${{ inputs.labels }}';
            const labels = labelsString.split(',').map(label => label.trim());
            await github.rest.issues.setLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ inputs.pr_number }},
              labels: labels
            });
